# Generated by Django 6.0.3 on 2026-03-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('emoji', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('automatica', 'Automática'), ('manual', 'Manual (Admin)')], default='automatica', max_length=20)),
                ('categoria', models.CharField(choices=[('posts', '📝 Posts'), ('likes', '❤️ Likes'), ('comentarios', '💬 Comentarios'), ('tiempo', '⏰ Tiempo'), ('especial', '⭐ Especial')], default='especial', max_length=20)),
                ('requisito_posts', models.IntegerField(default=0)),
                ('requisito_likes', models.IntegerField(default=0)),
                ('requisito_comentarios', models.IntegerField(default=0)),
                ('requisito_dias', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('color', models.CharField(default='#22c55e', max_length=20)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
                ('medalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logros.medalla')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'medalla')},
            },
        ),
    ]
