# Generated by Django 6.0.3 on 2026-03-17 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('faccion', models.CharField(choices=[('planta', '🌱 Plantas'), ('zombie', '🧟 Zombies'), ('neutral', '⚔️ Neutral')], default='neutral', max_length=10)),
                ('rango', models.CharField(choices=[('semilla', '🌱 Semilla'), ('girasol', '🌻 Girasol'), ('guerrero', '⚔️ Guerrero'), ('comandante', '🎖️ Comandante'), ('leyenda', '👑 Leyenda')], default='semilla', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
