# Generated by Django 6.0.3 on 2026-03-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='siguiendo', to='usuarios.perfil'),
        ),
    ]
