# Generated by Django 6.0.3 on 2026-03-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='semillas',
            field=models.IntegerField(default=0),
        ),
    ]
