# Generated by Django 6.0.3 on 2026-03-21 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfil_semillas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='color_nombre',
            field=models.CharField(choices=[('none', 'Normal'), ('verde', '🟢 Verde'), ('azul', '🔵 Azul'), ('rojo', '🔴 Rojo'), ('morado', '🟣 Morado'), ('dorado', '🟡 Dorado')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fondo_perfil',
            field=models.CharField(choices=[('none', 'Sin fondo'), ('galaxia', '🌌 Galaxia'), ('fuego', '🔥 Fuego'), ('matriz', '💻 Matriz')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='marco_avatar',
            field=models.CharField(choices=[('none', 'Sin marco'), ('dorado', '🎨 Marco Dorado'), ('diamante', '💎 Marco Diamante')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre_animado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_elite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultimo_login_bonus',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialSemillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ganado', '📈 Ganado'), ('gastado', '📉 Gastado')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_semillas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
