# Generated by Django 6.0.3 on 2026-03-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('faccion', models.CharField(choices=[('planta', 'Planta'), ('zombie', 'Zombie')], max_length=10)),
                ('rol', models.CharField(choices=[('ataque', 'Ataque'), ('soporte', 'Soporte'), ('defensa', 'Defensa'), ('control', 'Control')], max_length=10)),
                ('juego', models.CharField(choices=[('gw1', 'Garden Warfare 1'), ('gw2', 'Garden Warfare 2'), ('ambos', 'GW1 y GW2')], max_length=10)),
                ('descripcion', models.TextField()),
                ('dificultad', models.IntegerField(default=1)),
            ],
        ),
    ]
