# Generated by Django 6.0.3 on 2026-03-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='personajes/'),
        ),
    ]
