# Generated by Django 6.0.3 on 2026-03-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('juego', models.CharField(choices=[('gw1', 'Garden Warfare 1'), ('gw2', 'Garden Warfare 2'), ('ambos', 'GW1 y GW2')], max_length=10)),
                ('categoria', models.CharField(choices=[('personaje', 'Personaje'), ('mapa', 'Mapa'), ('gameplay', 'Gameplay'), ('arte', 'Arte')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
