# Generated by Django 6.0.3 on 2026-03-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fue_editado',
            field=models.BooleanField(default=False),
        ),
    ]
