# Generated by Django 6.0.3 on 2026-03-18 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_post_fue_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='foro.comentario'),
        ),
    ]
