# Generated by Django 6.0.3 on 2026-03-22 15:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_comentario_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
